### ISSUE TITLE
Coding/display problem

### ISSUE THREAD

**Issue by elviejito** [opennebraska/tif#11]
In the Omaha City TIF report 2015, the first item says "$4,003,179.66     No Number Assigned As Of This Report Period."  but looking up the TIF ID on the Dept. of Revenue 2015 PAD report comes back with "Name of Project: East Campus Realty, LLC
Midtown Crossing at Turner Park
Description: 23.30-acre Midtown Crossing mixed use development"
There are other display problems as well, but they may be resolved by dealing with this one.

**Comment by jhannah** [comment]
Hi Randolf, thank you. :) Looks like in 2008 that row had no info and my db_load.pl script doesn't audit / over-write if they fix it in later years (in this case, 2009-2015). I'm changing the program to overwrite, hoping the data always gets better over time...

**Comment by jhannah** [comment]
lol wow... LOTS of this data changes over time. The audit log is huge. Here's hoping the most recent is the best!
