### ISSUE TITLE
Make the 'About' link more obvious

### ISSUE THREAD

**Issue by jhannah** [opennebraska/tif#12]
@elviejito requested we change the 'About' link color to 250,245,117, 1. 

![yellow](https://cloud.githubusercontent.com/assets/62206/14531285/49b639c4-0222-11e6-9a74-43a80ebc78bf.jpg)

I like it, looks good. :) Also change the mouse-over color to a gold? (Currently grey.)

We'll be overriding Twitter Bootstrap defaults:

![tbs](https://cloud.githubusercontent.com/assets/62206/14531437/eecf1886-0222-11e6-9764-d94c6934e84d.jpg)

**Comment by jhannah** [comment]
Fixed by #14 :) Thanks!!

@awolfson FYI if you put "Fixes #14" in the git log message, it closes these automatically. :)

**Comment by awolfson** [comment]
Ohhh, that's some nice GitHub foo @jhannah!
