### ISSUE TITLE
Google Charts love needed

### ISSUE THREAD

**Issue by jhannah** [opennebraska/tif#13]
Hover over the graphs and you'll see ugly stuff like "2015 Taxes Refunded: 66271224.4599999". I [poked around in the docs](https://developers.google.com/chart/interactive/docs/customizing_charts) but couldn't figure out how to fix it.

**Comment by michaelherold** [comment]
Dumping these here to come back to later:

Formatters are what format the number for display.
https://developers.google.com/chart/interactive/docs/reference#formatters

Obligatory StackOverflow search that shows some of what we'll need.
http://stackoverflow.com/questions/7298685/formatting-google-charts-programmatically
