### ISSUE TITLE
New About.tt2

### ISSUE THREAD

**Issue by elviejito** [opennebraska/tif#16]
I just uploaded the latest about.tt2 to the master - templates code and pressed "commit".  Seems like something more or different needs to be done.

**Comment by jhannah** [comment]
You might find it easier to just click the Edit button, rather than uploading new files. :)

**Comment by elviejito** [comment]
I appreciate your patience.  I did just that. Let me know what you think.

```
 Jack
```

**Comment by elviejito** [comment]
I did the edit and clicked commit, but don't see any change.

```
 Jack
```

**Comment by jhannah** [comment]
@elviejito You're editing the template file. (Thank you!!) Someone has to run the site generator program and then commit, push those results for the Internet web site to change. I'll try to make that happen sometime today, after $day_job :)

**Comment by elviejito** [comment]
Thanks.  Today is pretty much already over for computer work for me.  
I'll be back again maybe tonight, more likely tomorrow.

```
 elviejito
```

**Comment by jhannah** [comment]
Changes applied. Thanks. :)
