### ISSUE TITLE
Whoops.  Major change in TIF Base and Excess Taxes.

### ISSUE THREAD

**Issue by elviejito** [opennebraska/tif#17]
For City: Bennington, County: Douglas, the text at the bottom:  $301,551.61     Dial-Ridgewood, LLC  represents only the total taxes paid in the year 2015.  Turns out, if we look at the PDF version of the 2015 TIF Report, the total Base taxes paid since 2007 are $29,706.63  and the Total TIF Excess Tax paid since 2007 come to $1,519,602.81.  This would be a change affecting all results in all Cities and Counties.  The graphs look correct;  just the totals are off.  Turns out we have to sum the Base Taxes and Excess Taxes for each instance of a TIF project.  Maybe the text at the bottom of the page can read (in green) Taxes Paid: (then in black) $29,706.63  (in red) Taxes Refunded: (then in black) $1,519,602.81 (followed by the link to the name of the development).  We could then put a similar line of text on the home page between the graphs and the Counties to show the Statewide totals. See page 9 of the 2015 TIF Report (PDF)  for comparison - http://www.revenue.nebraska.gov/PAD/research/tif_reports.html. My apologies for not catching this sooner.

**Comment by jhannah** [comment]
[The current source code](https://github.com/opennebraska/pri-tif/blob/master/static-www/scripts/generate_www.pl#L124) grabs the `max()` -- whatever year their highest refund was. We can change it to `sum()` easily, if you prefer that. 

It worries me to throw too many numbers of the page. Won't that look cluttered / confusing? Sticking with a single number per TIF strikes me as the way to go. My 2¢.

**Comment by elviejito** [comment]
I think there is a value in getting the taxes refunded and taxes paid 
numbers out on the page.  Let's see what it looks like;  we can always 
change it back.  And summing the taxes refunded and taxes paid gives a more accurate view of the last 15 or so years.

```
 Jack
```

**Comment by elviejito** [comment]
The changes look good!  Great work.

One further suggestion I have is to put a "City Total:  " under the list 
of Taxes Refunded and Taxes Paid that would sum each of those two 
columns for each city.

```
 Jack
```

P.S.  I'll only be able to put in little bits of time here and there 
between now and April 29.  We're preparing the basement for AIRBnB 
guests for the Berkshire Hathaway gathering, cleaning, painting, hauling 
away trash, etc.  plus my wife has a serious flu-like illness so I'm 
spending a fair amount of time taking care of her.

**Comment by jhannah** [comment]
@elviejito I added a city total row at the bottom. Done?

**Comment by jhannah** [comment]
@elviejito I also added totals to the individual TIF pages.

**Comment by elviejito** [comment]
Great!

```
 elviejito
```

**Comment by elviejito** [comment]
Great idea to add totals to each individual TIF page!

I also recommend adding totals to the main page - "Total for Nebraska:  "
     and to the County pages - "Total for _____ County:  "

And I think that is it!

At some point I would like to have a comment link available for anyone 
who subscribes on the PRI website to use (I am willing to moderate).  
This part may have to wait until PRI gets its website upgraded - 
hopefully in the next few weeks - unless there's a way to add comments 
onto the GitHub TIF db html.  I like the idea of setting up a free 
exchange of ideas about policy, politics, economics, land use, etc.

Also, I'd like to post a notice that the database raw data and code is 
available for download by request using either a Creative Commons 
license or a GPL version.  Let me know what you think.

```
 elviejito
```

**Comment by jhannah** [comment]
@elviejito let's open new issues for each of your desires, for discussion. I'll get us started.
