### ISSUE TITLE
Add Creative Commons or GPL license?

### ISSUE THREAD

**Issue by jhannah** [opennebraska/tif#19]
@elviejito said:

> I'd like to post a notice that the database raw data and code is available for download by request using either a Creative Commons license or a GPL version.  Let me know what you think.

I think licensing is confusing and time consuming. [There are lots of different CC licenses](https://creativecommons.org/faq/#Can_I_apply_a_Creative_Commons_license_to_software.3F), which one are you suggesting?

**Comment by elviejito** [comment]
I recommend the CC BY SA NC creative commons license:  attribution, 
share alike, non-commercial;  with attribution to Open Nebraska and PRI.

**Comment by natebenes** [comment]
You probably don't have the rights to claim a license over the raw data.  As for the code, Creative Commons doesn't recommend applying its licenses to software.  

> The only categories of works for which CC does not recommend its licenses are computer software and hardware. You should also not apply Creative Commons licenses to works that are no longer protected by copyright or are otherwise in the public domain.
> 
>  https://creativecommons.org/faq/

Perhaps you could select something from [choosealicense.com](http://choosealicense.com/)?

**Comment by elviejito** [comment]
I agree.  We can't claim a license over the data from the Dept. of 
Revenue.  The code, however, is a different story.

I first went to the GPL website only to note that it has very cumbersome 
requirements (a copy of the license with each file) and they don't 
recommend it for code of less than 300 lines.

So then I went to the Creative Commons website.  I did note that they do 
not recommend it for computer code and, in general, I can understand 
that;  although in our case, I think it would work just fine.  We're not 
producing a video game or complex CRM software. : )

GPL does recommend the Apache 2.0 license for small computer code.  
Given that they recommend it, I could sort of go along with using it 
although I tended to get lost among all the lawyerly jargon.

I would like to have some sort of copyleft arrangement for the code 
partly so it remains clear who produced it.  It could become 
well-distributed within a small circle of tax policy wonks.

**Comment by jhannah** [comment]
@elviejito wrote:
I'm going to withdraw my suggestion about using Copyleft for the C4N projects, mainly because, upon further reflection, it is somewhat complicated and there does not seem to be a need for it at this time.  Here are some URLs that go into more detail if anyone is interested.
https://en.wikipedia.org/wiki/Copyleft
https://en.wikipedia.org/wiki/Creative_Commons_license#Types_of_license
I've always loved the idea of Copyleft and like to spread it around, so I appreciate your indulging me.
