### ISSUE TITLE
Add PAD CSV to data.opennebraska.io?

### ISSUE THREAD

**Issue by jhannah** [opennebraska/tif#3]
Would that give us anything interesting, tool-wise?

(In previous years we used [Socrata](http://socrata.com))

**Comment by jhannah** [comment]
Hmm... [CSV seems to slurp in, but only 1000 lines](https://data.opennebraska.io/dataset/tif/resource/0d521285-79a6-4e03-92b8-57b55d4c7454)? @prefork @rnelson

**Comment by natebenes** [comment]
Copying from [Slack](https://openne.slack.com/):

> The UI only shows the first ​_n_​ rows.
> If you do a `curl https://data.opennebraska.io/dataset/6f993be8-6209-4060-ba17-4c81851bcc97/resource/0d521285-79a6-4e03-92b8-57b55d4c7454/download/tifreport2014.csv | wc -l` you should get 14104
