### ISSUE TITLE
Rename repo/project MORE-TIF?

### ISSUE THREAD

**Issue by jhannah-mm** [opennebraska/tif#33]
@elviejito now that PRI no longer exists / has been rebranded MORE, what should this repo be called? `tif`? `more-tif`? Something else? I'd like to update all the links and the repo name.

**Comment by jhannah-mm** [comment]
@elviejito said to just rename this `tif` for now since we don't yet know how involved MORE wants to be.

**Comment by jhannah** [comment]
Done.
