### ISSUE TITLE
Add 2020 data

### ISSUE THREAD

**Issue by jhannah-mm** [opennebraska/tif#34]
Looks like the [Department of Revenue](https://revenue.nebraska.gov/PAD/research-statistical-reports/tax-increment-financing-annual-reports-legislature) hasn't published the 2020 data yet. When they do we want to add it to the site.

**Comment by jhannah-mm** [comment]
I was super excited that the 2020 data appeared to be online. Unfortunately, it's broken. I sent them a message via their web portal:

> Hello. On your TIF page
>   https://revenue.nebraska.gov/PAD/research-statistical-reports/tax-increment-financing-annual-reports-legislature 
> Your 2020 download of PDF works.
> 2020 Excel download is listed in the drop-down. But trying to retrieve that Excel file is 404.

Hopefully they fix it soon.

**Comment by jhannah** [comment]
Yesterday 9am:
> Mr. Hannah, thank you for bringing this to our attention.
> This issue has been resolved and you should be able to open the 2020 TIF excel file now.
> Please let us know if you encounter any other issues.
> Have a great day!
>
> Cathy Gusman
> Tax Specialist Senior, Property Assessment Division

Looks good, looks like they didn't change the columns from 2019 so hopefully that means this'll go easy. :)

**Comment by jhannah** [comment]
Looks like I'm all done.
