### ISSUE TITLE
Prettier vertical axis? "$150M" vs. "$150,000,000.00"

### ISSUE THREAD

**Issue by jhannah** [opennebraska/tif#37]
This vertical axis looks pretty silly 
<img width="479" alt="Screen Shot 2021-03-05 at 9 36 32 AM" src="https://user-images.githubusercontent.com/62206/110137354-5d5eea80-7d96-11eb-82b0-bb6740d01961.png">

Anyone know how to make this less silly via `google.com/jsapi`? Or use some other charter?
https://github.com/codefornebraska/tif/blob/main/static-www/templates/chart.tt2#L2-L6

**Comment by sandikbarr** [comment]
You can use the `short` format instead of `currency` https://developers.google.com/chart/interactive/docs/customizing_axes
