### ISSUE TITLE
Host via SSL (https://)

### ISSUE THREAD

**Issue by jhannah** [opennebraska/tif#39]
@elviejito is getting browser warnings about our current `http://` hosting. Generate and install an SSL certificate on the current server (linode.com), or move the content (static web site) to Github Pages or some other hosting thing that does SSL.

Free SSL certs?
* https://letsencrypt.org/docs/
* https://www.netlify.com/

Don't break our virtual hosts:
* tif.report landing page for TIF around the world
* ne.tif.report (static web site)
* nebraska.tif.report (alias to ne)

**Comment by jhannah-mm** [comment]
@elviejito pinged me again on this. Apparently https://letsencrypt.org/ is how the Cool Kids are installing free wildcard (`*.tif.report`) SSL certificates nowadays.
```
apt-get update --allow-releaseinfo-change
apt-get install snapd
snap install core
ln -s /snap/bin/certbot /usr/local/bin/certbot
certbot certonly -d '*.tif.report' --manual --preferred-challenges dns

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/tif.report-0001/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/tif.report-0001/privkey.pem
This certificate expires on 2022-07-10.
These files will be updated when the certificate renews.

NEXT STEPS:
- This certificate will not be renewed automatically. Autorenewal of --manual certificates requires the use of an authentication hook script (--manual-auth-hook) but one was not provided. To renew this certificate, repeat this same certbot command before the certificate's expiry date.
```

Cheat sheet: https://levelup.gitconnected.com/obtaining-wildcard-ssl-from-lets-encrypt-fee9ea6ef2b3

**Comment by jhannah-mm** [comment]
Apache conf changes: https://github.com/jhannah/admin/commit/fa750b0ff56eec7c1edc8c440ed284b9d95b1111

**Comment by jhannah** [comment]
Seems to be working fine for a couple weeks. Closing.
