### ISSUE TITLE
PAD in Angular.js (Codepen)

### ISSUE THREAD

**Issue by reitmanj** [opennebraska/tif#4]
https://gist.github.com/reitmanj/6aef548c9090e249dbaf

**Comment by jhannah** [comment]
See the Joe's codepen in action: http://codepen.io/reitmanj/full/ojYbVJ/ 

Data source: http://www.revenue.nebraska.gov/PAD/research/tif_reports.html (PDF and XLS)

**Comment by jhannah** [comment]
I haven't seen @reitmanj in a while. I think he lost interest in the project. :(
