### ISSUE TITLE
PAD in flat html

### ISSUE THREAD

**Issue by jhannah** [opennebraska/tif#7]
Preview: http://opennebraska.github.io/pri-tif/

From /static-www using /db

**Comment by rnelson** [comment]
404 http://opennebraska.github.io/pri-tif/DOUGLAS/OMAHA/index.html

**Comment by jhannah** [comment]
yup, I haven't written the "show all TIFs in this city" loop yet.

**Comment by jhannah** [comment]
@rnelson fixed. The flat web sucks slightly less now. :+1:

**Comment by jhannah** [comment]
We're live. Yay! All done?
