### ISSUE TITLE
Bad data in TIF_REPORT_2008.xls

### ISSUE THREAD

**Issue by jhannah** [opennebraska/tif#8]
Hi Jack, please ask the PAD folks why when we download the 2008 XLS file from 

http://www.revenue.nebraska.gov/PAD/research/tif_reports.html

On lines 899-901, TIF ID # 24-0950 reports tax years 2007, 2008, 2008. 

No other data in this spreadsheet repeats a tax year on the same TIF ID. 

Thank you.

**Comment by elviejito** [comment]
Thanks.  Will do.
